// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  cameraId: __t.string().primaryKey().name("camera_id"),
  owner: __t.identity(),
  name: __t.string(),
  online: __t.bool(),
  lastSeen: __t.timestamp().name("last_seen"),
  chunkCount: __t.u32().name("chunk_count"),
});
