// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Answer = __t.object("Answer", {
  queryId: __t.u64(),
  text: __t.string(),
  citations: __t.string(),
  ts: __t.timestamp(),
});
export type Answer = __Infer<typeof Answer>;

export const Camera = __t.object("Camera", {
  cameraId: __t.string(),
  owner: __t.identity(),
  name: __t.string(),
  online: __t.bool(),
  lastSeen: __t.timestamp(),
  chunkCount: __t.u32(),
});
export type Camera = __Infer<typeof Camera>;

export const Chunk = __t.object("Chunk", {
  chunkId: __t.string(),
  cameraId: __t.string(),
  ts: __t.timestamp(),
  embedding: __t.array(__t.f32()),
  caption: __t.option(__t.string()),
  thumbB64: __t.string(),
});
export type Chunk = __Infer<typeof Chunk>;

export const LiveFrame = __t.object("LiveFrame", {
  cameraId: __t.string(),
  jpegB64: __t.string(),
  ts: __t.timestamp(),
});
export type LiveFrame = __Infer<typeof LiveFrame>;

export const PendingFrame = __t.object("PendingFrame", {
  id: __t.u64(),
  cameraId: __t.string(),
  jpegB64: __t.string(),
  ts: __t.timestamp(),
});
export type PendingFrame = __Infer<typeof PendingFrame>;

export const Query = __t.object("Query", {
  queryId: __t.u64(),
  asker: __t.identity(),
  text: __t.string(),
  ts: __t.timestamp(),
  answered: __t.bool(),
});
export type Query = __Infer<typeof Query>;

