// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import IngestFrameReducer from "../ingest_frame_reducer";
import RegisterCameraReducer from "../register_camera_reducer";
import StoreAnswerReducer from "../store_answer_reducer";
import StoreChunkReducer from "../store_chunk_reducer";
import SubmitQueryReducer from "../submit_query_reducer";

export type IngestFrameParams = __Infer<typeof IngestFrameReducer>;
export type RegisterCameraParams = __Infer<typeof RegisterCameraReducer>;
export type StoreAnswerParams = __Infer<typeof StoreAnswerReducer>;
export type StoreChunkParams = __Infer<typeof StoreChunkReducer>;
export type SubmitQueryParams = __Infer<typeof SubmitQueryReducer>;

